### ISSUE TITLE
Live site(s) not being updated

### ISSUE THREAD

**Issue by XhmikosR** [gruntjs/gruntjs.com#188] opened 2016-07-21 07:56 UTC
So it seems after the recent changes the live site(s) are not being updated anymore.

Not sure who's in charge of maintaining the server, so I make the issue to track the problem.

/CC @vladikoff

**Comment by dmethvin** [comment] 2016-07-21 13:02
Is this on a jQuery Foundation server now?

**Comment by XhmikosR** [comment] 2016-07-21 13:03
Yeah, I'd like to know more info too.

I could also maintain the server for gruntjs.com, if needed, since it doesn't require a lot of work as far as I can tell.

**Comment by vladikoff** [comment] 2016-07-21 13:24
> Is this on a jQuery Foundation server now?

Yeap!

> I could also maintain the server for gruntjs.com

Let's just leave the site where the rest of the jquery sites are hosted

**Comment by dmethvin** [comment] 2016-07-21 13:27
@aulvi is this maybe related to the issues we've had recently with the other sites? I think you were involved in moving the grunt site so you no doubt know a lot more about it.

**Comment by aulvi** [comment] 2016-07-21 17:03
@XhmikosR Hello! In order to update the production site, I think you need to tag a release.

**Comment by XhmikosR** [comment] 2016-07-21 17:03
Hmm, and I thought it might be it. But, shouldn't the staging site be updated even without a tag?

**Comment by aulvi** [comment] 2016-07-21 17:05
Yes, the staging site should be updating, and in fact it looks like it is. However, if you aren't seeing changes then the service may not be restarting correctly.

Could you take a look at http://stage.gruntjs.com/ and let me know if it's current? If not, I'll bounce it by hand and we can re-check.

**Comment by XhmikosR** [comment] 2016-07-21 17:07
@aulvi: it definitely isn't current that is why I started wondering.

Make sure you have node LTS on the server.

**Comment by aulvi** [comment] 2016-07-21 17:08
Okay I just bounced the service, please re-test.

Current installed node version is 4.2.6. If there is a particular version you wish to use, please let me know.

**Comment by XhmikosR** [comment] 2016-07-21 17:11
Still the same; it's not the current master.

**Comment by XhmikosR** [comment] 2016-07-21 17:14
Can you try updating to the latest Node.js LTS and then do:

```shell
npm cache clean
rm -rf ./node_modules/
npm i
```

Or show me some log to see what's wrong :)

**Comment by aulvi** [comment] 2016-07-21 17:14
```
$git status
HEAD detached at 946ccfe
```

That's what I'm seeing on the server atm.

**Comment by aulvi** [comment] 2016-07-21 17:15
Yeah I'll bump to the latest LTS. I need a few minutes, it's 10am on a Thursday for me and I'm at my job :) Hang tite maybe 30min.

**Comment by XhmikosR** [comment] 2016-07-21 17:17
Cool, no hurry now that you are aware :)

The hash is right, but for some reason the repo got messed up. So a `git checkout master` should fix it.

**Comment by aulvi** [comment] 2016-07-21 17:50
@XhmikosR @vladikoff LOL okay so I don't manage DNS for `gruntjs.com`. Looks like `stage.gruntjs.com` is pointed at the production server, which is why you aren't seeing updates. Just blew my mind haha!

**Comment by vladikoff** [comment] 2016-07-21 17:56
I don't think we changed DNS, I thought there was some nginx magic that picks the right domain.

I can swtich it though

**Comment by aulvi** [comment] 2016-07-21 18:00
@vladikoff No, there are two separate servers with two separate IP addresses. Nginx is there to take the traffic from :80 -> :3000 or whatever your node app lives on, but that's about it.

**Comment by vladikoff** [comment] 2016-07-21 19:08
@XhmikosR @aulvi updated to stage dns, try now

**Comment by XhmikosR** [comment] 2016-07-21 19:16
Now it works, but it appears the files need rebuild or something since the fonts are broken.

Also, should we change when the main site is updated? I find the tag procedure redundant personally.

**Comment by vladikoff** [comment] 2016-07-21 19:19
> Also, should we change when the main site is updated? I find the tag procedure redundant personally.

Stage builds on every commit. Tags deploy to production.

**Comment by XhmikosR** [comment] 2016-07-21 19:20
Or we have a staging branch and what is merged on master goes live.

**Comment by vladikoff** [comment] 2016-07-21 19:21
@XhmikosR that is confusing because `master` is what everyone sends PRs against.

**Comment by XhmikosR** [comment] 2016-07-21 19:22
Well, we can do the opposite then. Have a branch that we merge to from master when we want to go live.

**Comment by vladikoff** [comment] 2016-07-21 19:23
@XhmikosR sorry, it's just makes it confusing. think of it as plugin development. things get merged. then release is cut.

**Comment by XhmikosR** [comment] 2016-07-21 19:23
But it doesn't make sense to have releases for a website.

**Comment by XhmikosR** [comment] 2016-08-09 15:19
@aulvi: http://stage.gruntjs.com/ seems to have the fonts broken. Locally the master branch is OK.

**Comment by aulvi** [comment] 2016-08-19 21:47
@XhmikosR I don't know anything about the fonts, sorry, I just manage the server.

Can we close this issue or are we still having problems deploying the sites?

**Comment by XhmikosR** [comment] 2016-08-19 21:51
Well the deployment is wrong as you can see if you visit the stage site.
It's not from the latest master or it has some build issues which I cannot
solve since I don't have access to the server...

**Comment by aulvi** [comment] 2016-08-19 22:58
@XhmikosR Which commit hash are you expecting to see in staging? Here's what I'm seeing:

```
root@gruntjs:/var/www/gruntjs.com# git branch
* (detached from 6abf835)
```

That matches what is in master (afaik) and I confirmed the webhook works. Please let me know how I can help, thanks!

**Comment by XhmikosR** [comment] 2016-08-20 07:43
@aulvi: you can see that fonts are broken. Something is wrong with the deployment.

http://stage.gruntjs.com/

Can't you remove all repos and start again with node.js 4.x?

**Comment by XhmikosR** [comment] 2016-08-20 07:45
Because clearly, http://stage.gruntjs.com/ does **not** have the latest master commit.

**Comment by XhmikosR** [comment] 2017-01-15 07:10
@aulvi: ping. This is still an issue.

**Comment by vladikoff** [comment] 2017-01-17 23:17
@XhmikosR this should be fixed now 💃

**Closed by vladikoff** 2017-01-17 23:17 UTC

**Comment by XhmikosR** [comment] 2017-01-18 06:16
Woo hoo!
